"""Candidate-only Kraken-R constitutional foundation.

This package contains contracts and inspection tooling only. It does not
import, start, or adapt any legacy ROGAL runtime component.
"""

from .contracts import (
    Action,
    Authority,
    Capability,
    ContractValidationError,
    Decision,
    Event,
    Evidence,
    EvidenceGrade,
    ExecutionResult,
    GroundTruth,
    Hypothesis,
    LearningUpdate,
    Lineage,
    Mutation,
    Objective,
    Plan,
    Regression,
    Settlement,
    Signal,
    State,
    TaskState,
)
from .registry import (
    ArchitectureRegistry,
    ArchitectureRegistryError,
    MechanismRecord,
    RegistryAuthority,
    RegistryDisposition,
    RegistryStatus,
    ValidationReport,
    load_default_registry,
    load_registry,
)
from .cycle import (
    ConstitutionalCycle,
    CycleInvariantError,
    CycleMode,
    CycleTrace,
    DeterministicCycle,
    replay_constitutional_signal_path,
    run_constitutional_cycle,
    run_cycle,
)
from .nervous_system import (
    PropagationEffect,
    PropagationLimitError,
    PropagationTrace,
    SignalNetwork,
    SignalReplayRecord,
    SignalPropagationError,
    SignalRule,
    SignalStep,
    SignalValidationError,
    make_bound_signal,
    replay_signal_propagation,
)
from .replay import (
    RecordedExecution,
    RecordedExecutionMode,
    RecordedExecutionReplay,
    ReplayValidationError,
    replay_recorded_execution,
)

__all__ = [
    "Action",
    "ArchitectureRegistry",
    "ArchitectureRegistryError",
    "Authority",
    "Capability",
    "ConstitutionalCycle",
    "ContractValidationError",
    "CycleInvariantError",
    "CycleMode",
    "CycleTrace",
    "DeterministicCycle",
    "Decision",
    "Event",
    "Evidence",
    "EvidenceGrade",
    "ExecutionResult",
    "GroundTruth",
    "Hypothesis",
    "LearningUpdate",
    "Lineage",
    "Mutation",
    "Objective",
    "Plan",
    "PropagationEffect",
    "PropagationLimitError",
    "PropagationTrace",
    "Regression",
    "RecordedExecution",
    "RecordedExecutionMode",
    "RecordedExecutionReplay",
    "RegistryAuthority",
    "RegistryDisposition",
    "RegistryStatus",
    "Settlement",
    "Signal",
    "SignalNetwork",
    "SignalPropagationError",
    "SignalReplayRecord",
    "SignalRule",
    "SignalStep",
    "SignalValidationError",
    "State",
    "TaskState",
    "ValidationReport",
    "load_default_registry",
    "load_registry",
    "make_bound_signal",
    "replay_constitutional_signal_path",
    "run_constitutional_cycle",
    "run_cycle",
    "ReplayValidationError",
    "replay_recorded_execution",
    "replay_signal_propagation",
]